### ISSUE TITLE
[feature request] Add circle.yml to ignore gh-pages

### ISSUE THREAD

**Issue by JohannesHoppe** [angular-schule/angular-cli-ghpages#111]
It would be great if angular-cli-ghpages could add this file by default / by parameter. Because I'm pretty much sure that nobody wants to build a gh-pages branch on CircleCi.

see https://github.com/tony19/logback-android/commit/12f1d040c4eb2a7efda2d6ec123384b5d3565393

```
# Configuration for CircleCI

general:
  branches:
    ignore:
      - gh-pages
```
